<div class="well">
    <p class="lead">
        Welcome to Phavour
    </p>
    <p>
        Phavour is a blazingly fast, easy to use, exciting framework, built by developers like you.
    </p>
    <a href="<?php echo $this->urlFor('docs.quickStart'); ?>" class="btn btn-success block">
        &raquo; Quick Start
    </a>
</div>
<div class="well">
    <p class="lead">
        Contribute
    </p>
    <p>
        Whether it's finding a bug, or developing a new feature, you can find everything you need in our <a href="https://github.com/phavour">GitHub</a> repositories.
    </p>
    <a href="https://github.com/phavour" target="_blank" class="btn btn-primary block">
        &raquo; Visit Phavour on GitHub
    </a>
</div>